---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформлять и оплачивать заказы
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать законодательству страны
  - Стоимость товара и оплата товара должны производиться в одной валюте
  - Пользователь должен иметь возможность увеличивать изображение товара при просмотре
  - Пользователь должен иметь возможность выбирать нужную конфигурацию товара
  - Пользователь должен иметь возможность открывать карточку товара из корзины
  - Пользователь должен иметь возможность выбирать язык интерфейса
  - Изображения товара должны быть высокого качества и разрешения
  - Кнопки меню не должны отличаться друг от друга стилистически и по размеру
  - На сайте должно появляться всплывающее окошко об успешном добавлении товара в корзину
  - На сайте должен выполняться постраничный переход, если все товары нельзя отобразить на одной странице
  - Все иконки в меню должны отображаться корректно
  - Карточка каждого товара должна содержать краткую текстовую информацию о товаре и его характеристиках
