---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать законодательству страны
  - Сайт не должен нарушать элементарных законов математики, физики, логики
  - Сайт должен работать одинаково в любой день недели, месяца, года, и в любое время суток
  - Сайт должен скрывать пароль символами при авторизации и регистрации
  - Пользователь должен иметь возможность восстановить пароль
  - В поле номера телефона должно быть 10 цифр для ввода кода города
  - Стоимость товара и оплата товара должны производиться в одной валюте
  - Пользователь должен иметь возможность увеличивать изображение товара при просмотре
  - Пользователь должен иметь возможность выбирать нужную конфигурацию товара
  - Важно учитывать масштабирование при добавлении изображения в карточку товара
  - Изображения товара должны быть высокого качества и разрешения
  - Кнопки меню не должны отличаться друг от друга стилистически и по размеру
  - На сайте должно появляться всплывающее окошко об успешном добавлении товара в корзину
  - Все иконки в меню должны отображаться корректно
  - Карточка каждого товара должна содержать краткую текстовую информацию о товаре и его характеристиках
